### ISSUE TITLE
Update of P

### ISSUE THREAD

**Issue by AntoineGourru** [rrauber/Bayesian-Word-Vectors#2]
Hi,

Thank you for providing this implementation !

Just a little concern:
when you update P_u_new and P_v_new, the formulation seems different than Barkan's

wi.P_u_new += abs(d) * (2 * lambda_xi * eq + tau)

In the original paper, tau is added outside the sum:

![image](https://user-images.githubusercontent.com/33216464/56903564-d905f700-6a9c-11e9-98d6-8f07ae513429.png)

Maybe there is something I do not understand, if that's the case, sorry for bothering you 

Regards,
Antoine

**Comment by rrauber** [comment]
Hi Antoine! Thanks for raising this issue! I tried finding the line of code you were looking at in `bwv.py`, and it seems that at least as far as adding the tau is concerned I did it correctly there. Maybe you're looking at an older version? This definitely was an error at some point with my implementation but I picked it up in the "Debugging" commit on Mar 10, 2018.

This is the relevant part of the most recent version of the file:

<img width="640" alt="Screenshot 2019-04-30 at 09 01 22" src="https://user-images.githubusercontent.com/20564172/56967562-1020ea80-6b27-11e9-861b-801b1fa9c7f2.png">

Also thank you so much for the feedback! If you find anything else strange in my code please let me know!

Ross

**Comment by AntoineGourru** [comment]
Hi,

The error is in the notebook (Bayesian Word Embeddings.ipynb). Sorry I should have precise this and compare with the script file.

Thank you for your prompt response

Best regards,
Antoine

De : Ross Rauber
Envoyé le :mardi 30 avril 2019 16:10
À : rrauber/Bayesian-Word-Vectors
Cc : AntoineGourru; Author
Objet :Re: [rrauber/Bayesian-Word-Vectors] Update of P (#2)

Hi Antoine! Thanks for raising this issue! I tried finding the line of code you were looking at in bwv.py, and it seems that at least as far as adding the tau is concerned I did it correctly there. Maybe you're looking at an older version? This definitely was an error at some point with my implementation but I picked it up in the "Debugging" commit on Mar 10, 2018.
This is the relevant part of the most recent version of the file:

Also thank you so much for the feedback! If you find anything else strange in my code please let me know!
Ross

**Comment by rrauber** [comment]
ah, should have guessed that from the missing `self.` in the line you quoted. I was using the notebook for development and basically forgot it existed after a while. :) I just committed some changes removing the parallel implementation there and importing the classes necessary for a demo form `bwv.py`. 

Again, please let me know if anything else comes up! But for now I think I'll mark this one as closed.
